### ISSUE TITLE
frontend checklist

### ISSUE THREAD

**Issue by jjjpanda** [jjjpanda/Chimera#120]
- [x] #133
- [x] #134
- [x] #71 
- [x] #32
- [x] #87 
- [x] #30 
- [x] #136 
- [x] finishing touches and UI arrangement
- [x] https://github.com/jjjpanda/object/issues/8
- [ ] release prep with shrinkwraps
